# 10:20:00 onwards - NumPy Slicing

In [4]:
import numpy as np

In [5]:
# in numpy arrays:
# b = a[1:5] --> b is not a copy, it is accessing the same memory as a. 
# so if an element is changed in b, the corresponding element in a will be changed too.

# however, in list etc. structured arrays slicing results in a copy of the original array.

In [10]:
# indexing in 2d arrays in numpy:
a = np.arange(100)
b = a[3:10]
print(b)
b[0] = -1200
print(b)
print(a) # contents of a is also changedafter updating b
# the same memory is being accessed in a and b

[3 4 5 6 7 8 9]
[-1200     4     5     6     7     8     9]
[    0     1     2 -1200     4     5     6     7     8     9    10    11
    12    13    14    15    16    17    18    19    20    21    22    23
    24    25    26    27    28    29    30    31    32    33    34    35
    36    37    38    39    40    41    42    43    44    45    46    47
    48    49    50    51    52    53    54    55    56    57    58    59
    60    61    62    63    64    65    66    67    68    69    70    71
    72    73    74    75    76    77    78    79    80    81    82    83
    84    85    86    87    88    89    90    91    92    93    94    95
    96    97    98    99]


In [11]:
# with .copy, A and B can be used/updated seperately
A = np.arange(100)
B = A[3:10].copy()
A[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [15]:
# finding the index - looks throughout the array when (a == val) is True 
idx = np.argwhere(a==-1200)[0][0]
print(idx)

3


In [16]:
C = np.round(10*np.random.rand(5,4))
print(C)

[[ 0.  7.  7.  8.]
 [10.  7.  6.  8.]
 [ 0.  8.  6.  8.]
 [ 6.  9.  7.  6.]
 [ 6.  4.  2.  2.]]


In [18]:
# accessing a particular element:
C[1,2]

6.0

In [20]:
# accessing a complete row:
C[1,:]

array([10.,  7.,  6.,  8.])

In [22]:
# accessing a complete column:
C[:,1]

array([7., 7., 8., 9., 4.])

In [23]:
# accessing submatrices:
C[1:3,2:4] 

array([[6., 8.],
       [6., 8.]])

In [24]:
# transpose:
C.T

array([[ 0., 10.,  0.,  6.,  6.],
       [ 7.,  7.,  8.,  9.,  4.],
       [ 7.,  6.,  6.,  7.,  2.],
       [ 8.,  8.,  8.,  6.,  2.]])

In [31]:
# sorting in column/row individually:
# column:
C.sort(axis=0)
print(C)
print()
# row:
C.sort(axis=1) 
print(C)

[[ 0.  2.  2.  4.]
 [ 0.  6.  6.  7.]
 [ 6.  6.  7.  8.]
 [ 6.  7.  8.  8.]
 [ 7.  8.  9. 10.]]

[[ 0.  2.  2.  4.]
 [ 0.  6.  6.  7.]
 [ 6.  6.  7.  8.]
 [ 6.  7.  8.  8.]
 [ 7.  8.  9. 10.]]


In [25]:
# the linear algebra library in numpy:
import numpy.linalg as la

In [26]:
# inverse:
la.inv(np.random.rand(3,3))

array([[ -3.59181077,   3.47842937,   0.58962531],
       [ -9.95172068,  -1.87590946,  18.79896661],
       [ 12.06426411,  -0.27483899, -15.78678657]])

In [32]:
# index array:
F = np.arange(100)
G = F[[3,5,6]] # means pick the elements at index 3,5,6
G

array([3, 5, 6])

In [42]:
# picking elements using boolean:
# G = F[[True, False, False, False, True, True, False]]

In [44]:
H = F[F<40]
H

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [45]:
J = F[(F<40) & (F>30)]
J

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [46]:
# &, and 
# |, or
# ~, not

# 10:47:00 onwards - NumPy Broadcasting

In [48]:
L = np.round(10*np.random.rand(2,3))
L

array([[5., 4., 4.],
       [2., 7., 2.]])

In [49]:
L+3

array([[ 8.,  7.,  7.],
       [ 5., 10.,  5.]])

In [51]:
L+(np.arange(2).reshape(2,1))

array([[5., 4., 4.],
       [3., 8., 3.]])

In [52]:
K = np.round(10*np.random.rand(2,2))

In [62]:
# .hstack: concatenating two arrays horizontally
# .vtsack: concatenating two arrays vertically
print("K:")
print(K)
print()
print("L:")
print(L)
print()
I = np.hstack((L,K))
print("K+L (horizontally):")
I

K:
[[ 5.  1.]
 [10.  2.]]

L:
[[5. 4. 4.]
 [2. 7. 2.]]

K+L (horizontally):


array([[ 5.,  4.,  4.,  5.,  1.],
       [ 2.,  7.,  2., 10.,  2.]])

In [66]:
N = np.random.permutation(np.arange(10))
print(N)
N.sort()
print(N)
# or --> np.sort(N)

[6 3 9 8 7 1 5 4 0 2]
[0 1 2 3 4 5 6 7 8 9]


In [69]:
# sort in reversing order:
N = N[::-1]
N

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [70]:
M = np.array(["abc",'how are you','u765','13er'])
M.sort() #sorts in alphabetical order
M

array(['13er', 'abc', 'howare you', 'u765'], dtype='<U10')

# 10:58:00 onwards - Speed: Universal Functions

In [71]:
P = np.random.rand(1000000)
%timeit sum(P)
%timeit np.sum(P)  # B.sum()

143 ms ± 5.92 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
443 µs ± 30.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [76]:
def mySum(a):
    s = 0
    for x in a:
        s+=x
    return s

In [79]:
%timeit mySum(P)

189 ms ± 8.78 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
