# Movie Ratings Example

In [ ]:
"""
NumPy has many uses including:
- Efficiently working with many numbers at once
- Generating random numbers
- Performing many different numerical functions (i.e., calculating sin, cos, tan, mean, median, etc.)
"""

In [ ]:
"""
Twice Charred is a fictional (mostly) movie review site where four good friends and movie reviewers, 
Lorie, Marty, Tori, and Kurtz watch movies and give them ratings on a scale of 0 to 100. But they see 
more than one movie, so we have to create a 2-dimensional array where each row is their ratings for a 
specific movie. Some fans prefer to have the movies rated on a five star scale, find these movies scores.
Now let's say the ratings are always in the same order (Lorie, Marty, Tori, Kurtz) if we wanted to create 
an array that only had Tori's ratings, we could select that from our movie_ratings array. We find that we 
have very similar taste to Marty, so we only want to see movies that he gives a good rating to. Use logic 
to select those movies.
"""

In [21]:
import numpy as np
import pandas as pd

In [3]:
movie_ratings = np.array([63.0, 54.0, 70.0, 50.0])

In [26]:
reviewers = np.array(["Lorie", "Marty", "Tori", "Kurtz"])

In [5]:
individualRatings = np.array([[63.0, 36.0, 87.0],
                            [54.0, 55.0, 22.0],
                            [70.0, 78.0, 34.0],
                            [50.0, 65.0, 90.0]])

In [7]:
movieRatings = individualRatings/20
movieRatings

array([[3.15, 1.8 , 4.35],
       [2.7 , 2.75, 1.1 ],
       [3.5 , 3.9 , 1.7 ],
       [2.5 , 3.25, 4.5 ]])

In [12]:
TorisRatings = individualRatings[2,:]
TorisRatings

array([70., 78., 34.])

In [20]:
MartysRatings = individualRatings[1,:]
recommendedMovies = MartysRatings[MartysRatings>50]
recommendedMovies

array([54., 55.])

In [32]:
# converting numpy arrays to dictionaries:
# Ratings = dict(enumerate(individualRatings.flatten(), 1))
# Reviewer = dict(enumerate(reviewers.flatten(), 1))
# Ratings

In [60]:
Movies = ["Movie1", "Movie2", "Movie3"]
Lorie = {"Movie1":63.0, "Movie2":36.0, "Movie3":87.0}
Marty = {"Movie1":54.0, "Movie2":55.0, "Movie3":22.0}
Tori = {"Movie1":70.0, "Movie2":78.0, "Movie3":34.0}
Kurtz = {"Movie1":50.0, "Movie2":65.0, "Movie3":90.0}

avgMovie1 = (Lorie["Movie1"] + Marty["Movie1"] + Tori["Movie1"] + Kurtz["Movie1"])/4
avgMovie2 = (Lorie["Movie2"] + Marty["Movie2"] + Tori["Movie2"] + Kurtz["Movie2"])/4
avgMovie3 = (Lorie["Movie3"] + Marty["Movie3"] + Tori["Movie3"] + Kurtz["Movie3"])/4
Ratings = [avgMovie1, avgMovie2, avgMovie3]

In [61]:
ds = pd.DataFrame({"Movies":Movies, "Ratings":Ratings})
ds

Movies  Ratings
0  Movie1    59.25
1  Movie2    58.50
2  Movie3    58.25

In [53]:
Ld = pd.Series(Lorie)
L = Ld.values
Md = pd.Series(Marty)
M = Md.values
Td = pd.Series(Tori)
T = Td.values
Kd = pd.Series(Kurtz)
K = Kd.

In [54]:
detailedFrame = pd.DataFrame({"Movies":Movies, "Lorie":L, "Marty":M, "Tori":T, "Kurtz":K})
detailedFrame

Movies  Lorie  Marty  Tori  Kurtz
0  Movie1   63.0   54.0  70.0   50.0
1  Movie2   36.0   55.0  78.0   65.0
2  Movie3   87.0   22.0  34.0   90.0

In [62]:
finalFrame = pd.DataFrame({"Average Ratings":Ratings, "Lorie":L, "Marty":M, "Tori":T, "Kurtz":K})
finalFrame

Average Ratings  Lorie  Marty  Tori  Kurtz
0            59.25   63.0   54.0  70.0   50.0
1            58.50   36.0   55.0  78.0   65.0
2            58.25   87.0   22.0  34.0   90.0

In [ ]:
# finalFrame should involve Movie1, Movie2, Movie3 and not 0,1,2