In [1]:
"""
.csv importing:
we’re able to transform CSV (comma-separated values) files into arrays using the np.genfromtxt() function:
csv_array = np.genfromtxt('sample.csv', delimiter=',')
"""

In [5]:
import numpy as np

In [6]:
# operations:

# With a list:
l = [1, 2, 3, 4, 5]
l_plus_3 = []
for i in range(len(l)):
    l_plus_3.append(l[i] + 3)
    
# With an array:
a = np.array(l)
a_plus_3 = a + 3

In [8]:
c = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
c + b
# array([ 7,  9, 11, 13, 15])

array([ 7,  9, 11, 13, 15])

In [ ]:
"""In statistics, we often use two-dimensional arrays to represent a set of samples. For instance, if we flip a coin 
we can represent each head as a 1 and each tail as a 0. Create a one-dimensional array for a coin toss experiment that 
results in heads, tails, tails, heads, tails, and save it to the variable coin_toss.

We run the experiment again and get the following outcome: tails, tails, heads, heads, heads. Create a new array that 
represents both outcomes as a single experiment. Save the new array to coin_toss_again.
"""

In [18]:
coin_toss = np.array([1,0,0,1,0])
print("Coin toss:", coin_toss)
coin_toss_again = np.array([[1, 0, 0, 1, 0], [0, 0, 1, 1, 1]])
print("Coin toss again:", coin_toss_again)

Coin toss: [1 0 0 1 0]
Coin toss again: [[1 0 0 1 0]
 [0 0 1 1 1]]


In [19]:
toss_outcomes = np.array([[1,0],[0,1],[0,0],[1,1]])
toss_outcomes

array([[1, 0],
       [0, 1],
       [0, 0],
       [1, 1]])

In [20]:
# logical operations with arrays:
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
a > 5
# array([True, False, False, False, False, False, True, True, True, True], dtype=bool)

array([ True, False, False, False, False, False,  True,  True,  True,
        True])

In [21]:
a[a > 5]
# array([10, 9, 8, 9, 7])

array([10,  9,  8,  9,  7])

In [ ]:
"""
Today we’re visiting the Goldilocks Porridge Festival, sampling a selection of breakfast cereals and judging them 
based on their temperature (listed in Fahrenheit). Create a logical condition that selects samples in the porridge 
array that are less than 60, and save them to a variable named cold. Create a logical condition that finds all the 
samples that are higher than 80 and save them to a variable named hot. Create a logical condition that finds all the 
samples that are between 60 and 80 (inclusive) and save them to a variable named just_right. Print each array.
"""

In [22]:
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

cold = porridge[porridge<60]
hot = porridge[porridge>80]
just_right = porridge[(porridge>60) & (porridge<80)]
print(cold, hot, just_right)

[50 56 51] [90 85 98] [79 65 63 79]


In [ ]:
"""
You are working on a team of climate scientists and one of your roles is to take the weekly temperature data and 
input into NumPy arrays for later analysis. The sensor records the temperature 4 times a day, at 0:00, 6:00, 12:00, 
and 18:00. You are given last weeks data (Monday through Friday) and asked to create a NumPy array. One of the 
researchers noticed that the sensor had been incorrectly zeroed and all of the recorded temperatures are 3.0 degrees 
too cold. Adjust the array so that the temperature readings are accurate and save them to temperatures_fixed. Another 
researcher asked you for the temperature values from Monday. Save them to a new array, monday_temperatures. “Hmmm, 
interesting” the researcher mumbles, “can you also give me the 6:00 AM data for Thursday and Friday?” Save this data to 
a new array thursday_friday_morning. Finally, the persistent researcher wants all the high and low temperatures over the 
week. Select all temperatures that are under 50 degrees or over 60 degrees and save them to a new array temperature_extremes.
"""

In [33]:
temperatures = np.array([[43.6, 45.1, 58.8, 53.],
                         [47., 44.5, 58.3, 52.6],
                         [46.7, 44.2, 57.9, 52.2],
                         [46.5, 44.1, 57.6, 51.9],
                         [46.2, 43.9, 57.2, 51.5]])
temperatures_fixed = temperatures+3
print(temperatures_fixed)
monday_temperatures = temperatures_fixed[0,:]
thursday_friday_morning = temperatures_fixed[3:5,1]
temperature_extremes = temperatures_fixed[(temperatures_fixed<50) | (temperatures_fixed>60)]
print()
temperature_extremes

[[46.6 48.1 61.8 56. ]
 [50.  47.5 61.3 55.6]
 [49.7 47.2 60.9 55.2]
 [49.5 47.1 60.6 54.9]
 [49.2 46.9 60.2 54.5]]



array([46.6, 48.1, 61.8, 47.5, 61.3, 49.7, 47.2, 60.9, 49.5, 47.1, 60.6,
       49.2, 46.9, 60.2])

In [ ]:
# axis=0 are values that share an index (in the same column) and axis=1 are values share an array (in the same row).